name: 'Linting'
on: 
  pull_request:
    branches:
      - master
env:
    _TERRAFORM_VERSION: 1.0.4
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --user --no-warn-script-location -r tools/REQUIREMENTS.txt &&
          wget https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip &&
          unzip terraform_${_TERRAFORM_VERSION}_linux_amd64.zip -d $HOME/.local/bin &&
          rm terraform_${_TERRAFORM_VERSION}_linux_amd64.zip &&
          chmod 755 $HOME/.local/bin/terraform &&
          mkdir -p $HOME/.terraform.d/plugin-cache

      - name: Boilterplate
        id: boilerplate
        run: |
          python3 tools/check_boilerplate.py $GITHUB_WORKSPACE

      - name: Terraform Linting Check
        id: fmt
        run: |
          terraform fmt -recursive -check $GITHUB_WORKSPACE

      - name: Check documentation
        id: documentation
        run: |
          python3 tools/check_documentation.py cloud-operations/ data-solutions/ data-solutions/data-platform-foundations/ factories/ foundations/ modules/ networking/